sudo: false
language: java
jdk:
  - oraclejdk10
  - oraclejdk9
  - oraclejdk8
cache:
  directories:
    - "$HOME/.m2/repository"
before_cache:
  - rm -rf $HOME/.m2/repository/com/tersesystems
install:
- mvn --version